"""WebSocket media route for ACS audio bridge."""
from __future__ import annotations

from fastapi import APIRouter, WebSocket

from ..models.state import app_state
from ..services.call_manager import call_manager
from ..services.media_bridge import handle_media_ws

router = APIRouter(tags=["media"])


@router.websocket("/media/{token}")
async def media_ws(ws: WebSocket, token: str):
    """Bidirectional ACS ↔ Voice Live audio bridge.

    No password/session auth here — this endpoint is called by ACS
    infrastructure, not the browser.  The ``{token}`` path param is the
    operation-context token generated by ``_create_acs_call()`` and is used
    to correlate the WebSocket with the correct call session.
    """
    session_id = call_manager.get_session_id_for_media_token(token)
    await handle_media_ws(
        ws=ws,
        token=token,
        get_speech=lambda: call_manager.get_speech(session_id),
        app_state=app_state,
        session_id=session_id,
    )
